[package]
name = "lanfile-sendfile"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
salvo = { workspace = true, features = ["server", "http1"] }
tokio = { workspace = true, features = ["fs", "io-util", "net", "rt"] }
bytes = { workspace = true }
memchr = "2"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
rustix = { workspace = true, features = ["fs", "net", "std"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
