[package]
name = "filerserve-list"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
salvo = { workspace = true, features = ["server"] }
chrono = { workspace = true }
serde = { version = "1.0.229", features = ["derive"] }
if-addrs = "0.15"
rustix = { version = "1.1.5", features = ["fs"] }
arc-swap = "1.9"
