[package]
name = "lanfile-assets"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
lanfile-namedfile = { path = "../namedfile" }
lanfile-sendfile = { path = "../sendfile" }
salvo = { workspace = true, features = ["server", "serve-static"] }
mime = { workspace = true }
rust-embed = "8.12.0"
rustc-hash = "2.1.1"
tokio = { workspace = true, features = ["fs", "rt"] }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
rustix = { workspace = true, features = ["fs", "time"] }
